// Traduction des actions d'audit en phrases françaises lisibles (point 10).
// Chaque libellé se lit « <Acteur> <libellé> » : ex. « #11 Rita Moreau a émis un mandat ».

const LABELS: Record<string, string> = {
  // Effectif
  "agent.bootstrap_owner": "a initialisé le compte propriétaire",
  "agent.register": "s'est inscrit(e)",
  "agent.validate": "a validé un agent",
  "agent.reject": "a rejeté une inscription",
  "agent.grade_change": "a changé le grade d'un agent",
  "agent.matricule_change": "a changé le numéro de badge d'un agent",
  "agent.divisions_change": "a modifié les divisions d'un agent",
  "agent.qualifications_change": "a modifié les formations et spécialités d'un agent",
  "agent.date_entree": "a modifié la date d'arrivée d'un agent",
  "agent.deactivate": "a désactivé un agent",
  "agent.reactivate": "a réactivé un agent",
  "fiche.save": "a enregistré sa fiche de renseignement",
  "agent.password_reset": "a réinitialisé le mot de passe d'un agent",
  "agent.password_change": "a changé son mot de passe",
  "agent.lock": "a verrouillé un compte",
  "agent.unlock": "a déverrouillé un compte",
  // Citoyens
  "citizen.create": "a créé un dossier citoyen",
  "citizen.update": "a modifié l'identité d'un citoyen",
  "citizen.archive": "a archivé un dossier citoyen",
  "citizen.note_add": "a ajouté une note au dossier",
  "citizen.note_remove": "a supprimé une note du dossier",
  "citizen.flag_set": "a posé un signalement sur un citoyen",
  "citizen.flag_remove": "a retiré un signalement d'un citoyen",
  "citizen.license_set": "a délivré ou modifié une licence",
  "citizen.license_remove": "a retiré une licence",
  "citizen.relation_add": "a ajouté une relation entre citoyens",
  "citizen.relation_remove": "a retiré une relation entre citoyens",
  "deposition.create": "a enregistré une déposition",
  "deposition.delete": "a supprimé une déposition",
  // Véhicules et armes
  "vehicle.create": "a enregistré un véhicule",
  "vehicle.update": "a modifié un véhicule",
  "vehicle.delete": "a supprimé un véhicule",
  "flotte.create": "a ajouté un véhicule à la flotte",
  "flotte.edit": "a modifié un véhicule de la flotte",
  "flotte.delete": "a retiré un véhicule de la flotte",
  "vehicle.flag_set": "a posé un signalement sur un véhicule",
  "vehicle.flag_remove": "a retiré un signalement d'un véhicule",
  "weapon.create": "a enregistré une arme",
  "weapon.update": "a modifié une arme",
  "weapon.delete": "a supprimé une arme",
  // Casier et procédure
  "casier.entry_add": "a ajouté une entrée de casier",
  "casier.entry_delete": "a supprimé une entrée de casier",
  "casier.arrest_update": "a modifié un dossier d'arrestation",
  "casier.dossier_close": "a clôturé un dossier d'arrestation",
  "casier.dossier_reopen": "a rouvert un dossier d'arrestation",
  "citation.create": "a émis une contravention",
  "citation.delete": "a supprimé une contravention",
  "mandat.create": "a émis un mandat",
  "mandat.execute": "a exécuté un mandat",
  "mandat.delete": "a supprimé un mandat",
  "fine.paid": "a marqué une amende payée",
  "fine.unpaid": "a marqué une amende impayée",
  "saisie.create": "a enregistré une saisie",
  "saisie.delete": "a supprimé une saisie",
  "complaint.create": "a enregistré une plainte",
  "complaint.update": "a modifié une plainte",
  "complaint.delete": "a supprimé une plainte",
  // Avis de recherche
  "bolo.create": "a émis un avis de recherche",
  "bolo.close": "a levé un avis de recherche",
  // Service et RH
  "service.start": "a pris son service",
  "service.end": "a terminé son service",
  "service.cut": "a coupé un service",
  "service.edit": "a modifié un service",
  "service.remove": "a supprimé un service",
  "absence.request": "a demandé une absence",
  "discipline.create": "a ouvert un dossier disciplinaire",
  "discipline.close": "a clos un dossier disciplinaire",
  "discipline.remove": "a supprimé un dossier disciplinaire",
  // Rapports et documentation
  "report.create": "a créé un rapport",
  "report.submit": "a soumis un rapport",
  "report.validate": "a validé un rapport",
  "report.reopen": "a rouvert un rapport",
  "report.delete": "a supprimé un rapport",
  "protocole.create": "a créé un protocole",
  "protocole.edit": "a modifié un protocole",
  "protocole.delete": "a supprimé un protocole",
  "resource.create": "a créé une ressource",
  "resource.edit": "a modifié une ressource",
  "resource.delete": "a supprimé une ressource",
  "calendar.create": "a créé un évènement",
  "calendar.remove": "a supprimé un évènement",
  // Configuration
  "defcon.change": "a changé le niveau DEFCON",
  "permission.grant": "a accordé une permission",
  "permission.revoke": "a retiré une permission",
  "invite.create": "a généré une invitation",
  "invite.revoke": "a révoqué une invitation",
  "grade.create": "a créé un grade",
  "grade.update": "a modifié un grade",
  "grade.delete": "a supprimé un grade",
  "codepenal.category_create": "a créé une catégorie du code pénal",
  "codepenal.category_update": "a modifié une catégorie du code pénal",
  "codepenal.category_remove": "a supprimé une catégorie du code pénal",
  "codepenal.charge_create": "a ajouté une infraction",
  "codepenal.charge_update": "a modifié une infraction",
  "codepenal.charge_remove": "a supprimé une infraction",
  "carte.set_image": "a changé le fond de carte",
  "carte.add_location": "a ajouté un lieu sur la carte",
  "carte.remove_location": "a retiré un lieu de la carte",
  "webhook.create": "a créé un webhook Discord",
  "webhook.update": "a modifié un webhook Discord",
  "webhook.delete": "a supprimé un webhook Discord",
  "webhook.bot_config": "a modifié la configuration du bot Discord",
  "webhook.base_url": "a modifié l'URL de base du MDT",
  // Effectif (compléments)
  "agent.name_change": "a modifié l'identité RP d'un agent",
  "agent.login_change": "a modifié l'identifiant de connexion d'un agent",
  "agent.iban_change": "a modifié l'IBAN d'un agent",
  "agent.phone_change": "a modifié le téléphone d'un agent",
  // Citoyens (compléments)
  "citizen.deceased": "a déclaré un citoyen décédé",
  "citizen.revived": "a annulé le décès d'un citoyen",
  "citizen.aliases": "a modifié les alias d'un citoyen",
  "citizen.restore": "a restauré un dossier citoyen",
  // Casier / finances (compléments)
  "casier.charges_update": "a modifié les charges d'une entrée de casier",
  "citation.charges_update": "a modifié les charges d'une contravention",
  "amende.status": "a changé le statut d'une amende",
  // Fiches 911
  "call911.create": "a créé une fiche d'appel 911",
  "call911.edit": "a modifié une fiche d'appel 911",
  "call911.status": "a changé le statut d'une fiche 911",
  "call911.delete": "a supprimé une fiche d'appel 911",
  // Absences (compléments)
  "absence.create_for": "a déclaré une absence pour un agent",
  "absence.update": "a modifié une absence",
  "absence.delete": "a annulé une absence",
  "absence.approve": "a approuvé une absence",
  "absence.reject": "a refusé une absence",
  // Discipline / IA (compléments)
  "discipline.reactivate": "a levé une mise à pied",
  "discipline.evidence": "a modifié les preuves d'une sanction",
  "convocation.create": "a émis une convocation",
  "convocation.remove": "a supprimé une convocation",
  "investigation.create": "a ouvert une enquête interne",
  "investigation.close": "a clôturé une enquête interne",
  "investigation.remove": "a supprimé une enquête interne",
  // Cérémonies
  "ceremony.create": "a créé une cérémonie",
  "ceremony.update": "a modifié une cérémonie",
  "ceremony.remove": "a supprimé une cérémonie",
  "ceremony.discord_promote": "a lancé les montées en grade Discord d'une cérémonie",
  "ceremony.apply_grades": "a appliqué les montées en grade d'une cérémonie",
  "ceremony.announce": "a publié l'annonce d'une cérémonie",
  "ceremony.announce_result": "a publié le compte-rendu d'une cérémonie",
  // Académie (LSPA)
  "lspa.rank_change": "a modifié un grade d'académie",
  "lspa.quiz_create": "a créé un quiz",
  "lspa.quiz_delete": "a supprimé un quiz",
  "lspa.session_open": "a ouvert une session de quiz",
  "lspa.session_publish": "a publié les résultats d'une session",
  "lspa.session_delete": "a supprimé une session de quiz",
  "lspa.promo_create": "a créé une promotion",
  "lspa.promo_delete": "a supprimé une promotion",
  "lspa.promo_graduate": "a diplômé un cadet",
  "interview.create": "a créé un entretien",
  "interview.delete": "a supprimé un entretien",
  // Espace division
  "division.set_module": "a modifié les modules d'une division",
  "division.set_lead": "a désigné le Lead d'une division",
  "division.set_description": "a modifié la description d'une division",
  "division.set_logo": "a modifié le logo d'une division",
  "division.rank_create": "a créé un grade interne de division",
  "division.rank_update": "a modifié un grade interne de division",
  "division.rank_remove": "a supprimé un grade interne de division",
  "division.rank_perms": "a modifié les permissions d'un grade de division",
  "division.member_rank": "a modifié le grade interne d'un membre",
  "division.announce": "a publié une annonce de division",
  "division.announce_remove": "a supprimé une annonce de division",
  // Comptabilité / salaires
  "payroll.scale_save": "a modifié un barème de salaire",
  "payroll.scale_delete": "a supprimé un barème de salaire",
  "payroll.bonus_add": "a ajouté une prime",
  "payroll.bonus_delete": "a supprimé une prime",
  "payroll.set_paid": "a modifié l'état de paiement d'un salaire",
  "payroll.pay_all": "a versé tous les salaires de la semaine",
  // Liaison Discord / Nexus
  "discord.send_account": "a envoyé un compte à un membre Discord",
  "discord.link": "a relié un agent à un compte Discord",
  "discord.unlink": "a délié un agent de son compte Discord",
  "discord.sync_role": "a synchronisé le rôle Discord d'un grade",
  "discord.command_access": "a modifié l'accès à une commande Discord",
  "nexus.credential_save": "a enregistré ses identifiants Nexus",
  "nexus.credential_remove": "a délié un compte Nexus",
  "nexus.password_reveal": "a révélé son mot de passe Nexus",
  // Configuration (compléments)
  "permission.copy": "a copié les permissions d'un grade",
  "permission.grant_all": "a accordé une permission à tous les grades",
  "permission.revoke_all": "a retiré une permission à tous les grades",
  "reglement.update": "a mis à jour le règlement",
  "tenue.save": "a enregistré une tenue",
  "tenue.delete": "a supprimé une tenue",
  // Dispatch
  "dispatch.patrol_create": "a créé une patrouille",
  "dispatch.patrol_dissolve": "a dissous une patrouille",
  "dispatch.operation_create": "a lancé une opération",
  "dispatch.operation_end": "a terminé une opération",
  "dispatch.status_save": "a modifié un statut de dispatch",
  "dispatch.status_remove": "a supprimé un statut de dispatch",
  "dispatch.sector_save": "a modifié un secteur de dispatch",
  "dispatch.sector_remove": "a supprimé un secteur de dispatch",
  // Correction académie (fiche de notation cadet)
  "grading.item_save": "a modifié un critère de la fiche de notation",
  "grading.item_remove": "a supprimé un critère de la fiche de notation",
  "grading.item_move": "a réordonné un critère de la fiche de notation",
  "grading.seed": "a initialisé la fiche de notation par défaut",
  "grading.entry_set": "a noté un cadet sur un critère",
  "grading.note_add": "a ajouté une note sur un cadet",
  "grading.note_remove": "a supprimé une note sur un cadet",
  "grading.bonus_set": "a modifié le bonus/malus d'un cadet",
  "grading.conclusion_set": "a modifié la conclusion d'un cadet",
  // First Lincoln
  "firstlincoln.config": "a modifié la config First Lincoln",
  "firstlincoln.eval_save": "a enregistré une évaluation First Lincoln",
  "firstlincoln.eval_remove": "a supprimé une évaluation First Lincoln",
  "firstlincoln.criterion_save": "a modifié un critère First Lincoln",
  "firstlincoln.criterion_remove": "a supprimé un critère First Lincoln",
  "firstlincoln.criterion_move": "a réordonné un critère First Lincoln",
  "firstlincoln.seed": "a initialisé la grille First Lincoln par défaut",
  // FTO (Formation Terrain)
  "fto.item_save": "a modifié un critère de la fiche FTO",
  "fto.item_remove": "a supprimé un critère de la fiche FTO",
  "fto.item_move": "a réordonné un critère de la fiche FTO",
  "fto.seed": "a initialisé la fiche FTO par défaut",
  "fto.config": "a modifié la configuration FTO",
  "fto.auto_assign": "a auto-attribué les tuteurs FTO",
  "fto.announce": "a publié l'annonce des tuteurs FTO",
  // Espace division (complément)
  "division.rank_move": "a réordonné un grade interne de division",
  // Rapports (compléments : édition de contenu)
  "report.content_update": "a modifié le contenu d'un rapport",
  "report.open": "s'est ajouté(e) comme agent impliqué au rapport",
  "report.contributor_add": "a ajouté un agent impliqué au rapport",
  "report.contributor_remove": "a retiré un agent impliqué du rapport",
  "report.suspect_add": "a ajouté un suspect au rapport",
  "report.suspect_remove": "a retiré un suspect du rapport",
  "report.role_set": "a attribué un rôle sur le rapport",
  "report.hostage_add": "a ajouté un otage au rapport",
  "report.hostage_update": "a modifié un otage du rapport",
  "report.hostage_remove": "a retiré un otage du rapport",
  "report.hostage_deposition": "a lié la déposition d'un otage",
  // Sessions de quiz (compléments)
  "lspa.session_start": "a lancé une session de quiz",
  "lspa.session_close": "a terminé une session de quiz",
  "lspa.session_cancel": "a annulé une session de quiz",
  "lspa.session_grade": "a corrigé une copie de quiz",
  // Banque d'entretiens
  "interviewitem.create": "a ajouté une question à la banque d'entretien",
  "interviewitem.update": "a modifié une question de la banque d'entretien",
  "interviewitem.toggle": "a activé/désactivé une question d'entretien",
  "interviewitem.remove": "a supprimé une question de la banque d'entretien",
  "interviewitem.move": "a réordonné une question d'entretien",
  "interview.update": "a modifié un entretien",
  // Bureau des enquêtes (Detective) - enquêtes
  "detective.case_create": "a créé une enquête",
  "detective.case_update": "a modifié une enquête",
  "detective.case_status": "a changé le statut d'une enquête",
  "detective.case_synthesis": "a modifié la synthèse d'une enquête",
  "detective.case_delete": "a supprimé une enquête",
  "detective.team_add": "a ajouté un agent à l'équipe d'enquête",
  "detective.team_remove": "a retiré un agent de l'équipe d'enquête",
  "detective.timeline_add": "a ajouté un évènement à la chronologie",
  "detective.timeline_remove": "a supprimé un évènement de la chronologie",
  "detective.todo_add": "a ajouté une piste",
  "detective.todo_toggle": "a coché/décoché une piste",
  "detective.todo_remove": "a supprimé une piste",
  "detective.folder_add": "a créé un sous-dossier",
  "detective.folder_rename": "a renommé un sous-dossier",
  "detective.folder_remove": "a supprimé un sous-dossier",
  "detective.item_add": "a ajouté une pièce au dossier",
  "detective.item_update": "a modifié une pièce du dossier",
  "detective.item_remove": "a supprimé une pièce du dossier",
  "detective.evidence_add": "a scellé une preuve",
  "detective.evidence_update": "a modifié une preuve",
  "detective.evidence_remove": "a supprimé une preuve",
  "detective.vehicle_add": "a lié un véhicule à l'enquête",
  "detective.vehicle_remove": "a retiré un véhicule de l'enquête",
  "detective.board_node_add": "a ajouté un nœud au tableau d'enquête",
  "detective.board_node_move": "a déplacé un nœud du tableau d'enquête",
  "detective.board_node_update": "a modifié un nœud du tableau d'enquête",
  "detective.board_node_remove": "a supprimé un nœud du tableau d'enquête",
  "detective.board_edge_add": "a relié deux nœuds du tableau d'enquête",
  "detective.board_edge_update": "a modifié un lien du tableau d'enquête",
  "detective.board_edge_remove": "a supprimé un lien du tableau d'enquête",
  // Bureau des enquêtes (Detective) - gangs, registre, surveillance
  "detective.gang_create": "a créé un gang / une organisation",
  "detective.gang_update": "a modifié un gang / une organisation",
  "detective.gang_delete": "a supprimé un gang / une organisation",
  "detective.gang_rank_create": "a créé un grade de gang",
  "detective.gang_rank_rename": "a renommé un grade de gang",
  "detective.gang_rank_move": "a réordonné un grade de gang",
  "detective.gang_rank_delete": "a supprimé un grade de gang",
  "detective.gang_member_set": "a affecté un membre à un gang",
  "detective.gang_relation_set": "a défini une relation entre gangs",
  "detective.gang_relation_remove": "a supprimé une relation entre gangs",
  "detective.gang_hq_set": "a défini le QG d'un gang",
  "detective.territory_add": "a ajouté un territoire",
  "detective.territory_remove": "a supprimé un territoire",
  "detective.case_gang_add": "a lié un gang à une enquête",
  "detective.case_gang_remove": "a délié un gang d'une enquête",
  "detective.drugsite_create": "a créé un point stupéfiants",
  "detective.drugsite_update": "a modifié un point stupéfiants",
  "detective.drugsite_delete": "a supprimé un point stupéfiants",
  "detective.person_create": "a créé une personne au registre",
  "detective.person_update": "a modifié une personne du registre",
  "detective.person_delete": "a supprimé une personne du registre",
  "detective.case_person_add": "a lié une personne à une enquête",
  "detective.case_person_update": "a modifié une personne liée à une enquête",
  "detective.case_person_remove": "a délié une personne d'une enquête",
  "detective.surveillance_create": "a créé une surveillance",
  "detective.surveillance_update": "a modifié une surveillance",
  "detective.surveillance_delete": "a supprimé une surveillance",
  // Archive
  "archive.restore": "a restauré un élément archivé",
  "archive.purge": "a purgé définitivement un élément archivé",
};

export function actionLabel(action: string): string {
  if (LABELS[action]) return LABELS[action];
  // Référentiels de configuration : action dynamique « config.<table>.<op> ».
  const cfg = /^config\.(.+)\.(create|update|remove)$/.exec(action);
  if (cfg) {
    const verb = cfg[2] === "create" ? "a créé" : cfg[2] === "update" ? "a modifié" : "a supprimé";
    return `${verb} un élément de configuration`;
  }
  return action;
}

// Type de ressource en français (colonne / détail).
const RESOURCE_LABELS: Record<string, string> = {
  agent: "Agent",
  citizen: "Citoyen",
  citizenNote: "Note",
  vehicle: "Véhicule",
  fleetVehicle: "Véhicule LSPD",
  weapon: "Arme",
  casierEntry: "Entrée de casier",
  citation: "Contravention",
  mandat: "Mandat",
  bolo: "Avis de recherche",
  complaint: "Plainte",
  deposition: "Déposition",
  saisie: "Saisie",
  defcon: "DEFCON",
  permission: "Permission",
  invitation: "Invitation",
  grade: "Grade",
  config: "Configuration",
  webhook: "Webhook Discord",
  service: "Service",
  serviceSession: "Service",
  absence: "Absence",
  discipline: "Discipline",
  protocol: "Protocole",
  resource: "Ressource",
  tenue: "Tenue",
  report: "Rapport",
  calendarEvent: "Évènement",
  operation: "Opération",
  patrol: "Patrouille",
  amende: "Amende",
  call911: "Fiche 911",
  ceremony: "Cérémonie",
  convocation: "Convocation",
  division: "Division",
  interview: "Entretien",
  investigation: "Enquête interne",
  promotion: "Promotion",
  quiz: "Quiz",
  quizSession: "Session de quiz",
  document: "Document",
  reglement: "Règlement",
  payScale: "Barème de salaire",
  salaryBonus: "Prime",
  nexusCredential: "Compte Nexus",
  discordCommandAccess: "Commande Discord",
  divisionRank: "Grade de division",
  divisionAnnouncement: "Annonce de division",
  gradingItem: "Critère de notation",
  gradingEntry: "Note de cadet",
  cadetNote: "Note de cadet",
  flEvaluation: "Éval. First Lincoln",
  flCriterion: "Critère First Lincoln",
  ftoItem: "Critère FTO",
  ftoPatrol: "Patrouille FTO",
  ftoSheet: "Fiche FTO",
  interviewItem: "Question d'entretien",
  // Bureau des enquêtes (Detective)
  dbCase: "Enquête",
  dbCaseTeam: "Équipe d'enquête",
  dbCaseVehicle: "Véhicule d'enquête",
  dbTimeline: "Chronologie d'enquête",
  dbTodo: "Piste d'enquête",
  dbFolder: "Sous-dossier d'enquête",
  dbItem: "Pièce de dossier",
  dbEvidence: "Preuve",
  dbBoardNode: "Nœud du tableau d'enquête",
  dbBoardEdge: "Lien du tableau d'enquête",
  dbGang: "Gang / organisation",
  dbGangRank: "Grade de gang",
  dbGangTerritory: "Territoire de gang",
  dbCaseGang: "Gang d'enquête",
  dbPerson: "Personne (registre)",
  dbCasePerson: "Personne d'enquête",
  dbDrugSite: "Point stupéfiants",
  dbSurveillance: "Surveillance",
};

export function resourceLabel(type: string): string {
  return RESOURCE_LABELS[type] ?? type;
}

// Libellé lisible d'un champ pour le diff avant/après.
const FIELD_LABELS: Record<string, string> = {
  nom: "Nom",
  prenom: "Prénom",
  empreinte: "Empreinte",
  dateNaissance: "Date de naissance",
  sexe: "Sexe",
  nationalite: "Nationalité",
  telephone: "Téléphone",
  adresse: "Adresse",
  metier: "Métier",
  employeur: "Employeur",
  plaque: "Plaque",
  modele: "Modèle",
  couleur: "Couleur",
  motif: "Motif",
  status: "Statut",
  totalFine: "Amende totale",
  totalJailSeconds: "Prison (s)",
  charges: "Charges",
  lieu: "Lieu",
};

export function fieldLabel(key: string): string {
  return FIELD_LABELS[key] ?? key;
}
